# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build both corne sides, qwerty, win clipboard, mouse PR enabled, increase BT radio, use display'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["qwerty"]'
      clipboard: '["win"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll","zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y", "CONFIG_ZMK_MOUSE=y", "CONFIG_ZMK_DISPLAY=y"]'